import { ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { MaterialCommunityIcons } from '@expo/vector-icons';

export default function TermsScreen({ navigation }) {
  return (
    <View style={styles.container}>
      <TouchableOpacity style={styles.back} onPress={() => navigation.goBack()} activeOpacity={0.7}>
        <MaterialCommunityIcons name="chevron-left" size={22} color="#0F6E56" />
        <Text style={styles.backText}>Back</Text>
      </TouchableOpacity>

      <ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
        <Text style={styles.title}>Terms of Service</Text>
        <Text style={styles.lastUpdated}>Last updated: July 22, 2026</Text>

        <Section heading="1. Acceptance of Terms">
          By downloading, accessing, or using Know Better, you agree to be bound by these Terms of Service. If you do not agree, do not use the app.{'\n\n'}We may update these Terms from time to time. Continued use of Know Better after changes are posted constitutes acceptance of the revised Terms. We will notify you of material changes via the app or email.
        </Section>

        <Section heading="2. What Know Better Is (and Is Not)">
          Know Better is a behavioral pattern detection tool for dog owners. It helps you log observations about your dog, identify patterns over time, and receive alerts when those patterns suggest something may be worth investigating.{'\n\n'}Know Better is not a medical diagnostic service, not a veterinary service, and not a substitute for professional veterinary care.{'\n\n'}Alerts and insights generated by Know Better are informational suggestions based on pattern detection. They are not diagnoses, treatment recommendations, or medical opinions. Always consult a licensed veterinarian for any health concerns about your dog.
        </Section>

        <Section heading="3. Health Disclaimer">
          Know Better cannot diagnose, treat, prevent, or cure any medical condition in your dog. The app uses AI-powered pattern detection to flag behavioral trends — it does not have access to physical examination findings, lab results, imaging, or any other clinical data.{'\n\n'}An alert from Know Better does not mean your dog is sick. The absence of an alert does not mean your dog is healthy. Pattern detection is probabilistic, not guaranteed.{'\n\n'}Do not delay or avoid seeking veterinary care based on anything Know Better tells you. Always rely on a licensed veterinary professional for health-related decisions about your dog.
        </Section>

        <Section heading="4. User Responsibilities">
          <SubSection heading="Accurate information">
            You agree to provide accurate, complete information when logging check-ins and setting up your dog's profile. Do not enter false or misleading information. The quality of Know Better's pattern detection depends on the accuracy of what you log.
          </SubSection>
          <SubSection heading="Account security">
            You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. Notify us immediately at knowbettersupport@gmail.com if you suspect unauthorized access.
          </SubSection>
          <SubSection heading="Appropriate use">
            You agree to use Know Better only for its intended purpose — tracking your own dog's behavioral health. You may not use the app to harass, deceive, or harm others, or for any unlawful purpose.
          </SubSection>
          <SubSection heading="Your data">
            You are solely responsible for the check-in notes, voice recordings, and other content you submit through the app.
          </SubSection>
        </Section>

        <Section heading="5. Intellectual Property">
          Know Better and all its content — including the app design, AI models, pattern detection logic, and underlying software — are the intellectual property of Know Better and are protected by applicable law.{'\n\n'}You retain full ownership of the data you submit, including check-in notes and photos. By using the service, you grant Know Better a limited license to process and store your data for the sole purpose of providing the service to you. We do not claim ownership of your content.
        </Section>

        <Section heading="6. Third-Party Services">
          Know Better integrates with third-party services to operate:{'\n\n' +
          'Anthropic (Claude API) — AI analysis of check-in text\n' +
          'Supabase — data storage and authentication\n' +
          'Sentry — crash reporting\n' +
          'Langfuse — API performance monitoring\n\n' +
          'Each of these services operates under its own terms and privacy policies. We are not responsible for the practices of third-party providers.'}
        </Section>

        <Section heading="7. Disclaimer of Warranties">
          Know Better is provided "as is" and "as available" without warranties of any kind, express or implied.{'\n\n'}We do not warrant that the service will be uninterrupted, error-free, or secure; that pattern detection results will be accurate or reliable; that alerts will be triggered for every health concern; or that the app will meet your specific requirements.{'\n\n'}To the fullest extent permitted by law, we disclaim all implied warranties, including merchantability, fitness for a particular purpose, and non-infringement.
        </Section>

        <Section heading="8. Limitation of Liability">
          To the fullest extent permitted by applicable law, Know Better and its founders, employees, and agents shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the service — including missed or false alerts, misclassification of check-in data, decisions made based on app insights, delays in seeking veterinary care, or loss of data.{'\n\n'}Our total liability to you for any claim shall not exceed the fees you paid to us in the 12 months preceding the claim, or $10 USD, whichever is greater.
        </Section>

        <Section heading="9. Indemnification">
          You agree to indemnify and hold harmless Know Better and its founders, employees, and agents from any claims, damages, losses, or expenses (including reasonable legal fees) arising out of your use of the service, your violation of these Terms, your infringement of any third party's rights, or any content you submit through the app.
        </Section>

        <Section heading="10. Termination">
          You may delete your account at any time by contacting knowbettersupport@gmail.com. Your data will be removed within 30 days as described in our Privacy Policy.{'\n\n'}We may suspend or terminate your account if you violate these Terms or for any other reason with reasonable notice. We may also discontinue the service entirely, in which case we will provide advance notice where possible.{'\n\n'}Sections 7, 8, and 9 of these Terms survive termination.
        </Section>

        <Section heading="11. Changes to the Service">
          We may add, modify, or remove features at any time. We will notify users of material changes via the app or email and will aim to provide reasonable notice before significant changes take effect.
        </Section>

        <Section heading="12. Governing Law">
          These Terms are governed by the laws of the Commonwealth of Pennsylvania, without regard to conflict of law principles. Any disputes arising from these Terms or your use of Know Better shall be resolved in the state or federal courts located in Pennsylvania, and you consent to personal jurisdiction in those courts.
        </Section>

        <Section heading="13. Contact Us">
          Questions about these Terms? Email us at knowbettersupport@gmail.com. We aim to respond to all inquiries within 5 business days.
        </Section>
      </ScrollView>
    </View>
  );
}

function Section({ heading, children }) {
  return (
    <View style={styles.section}>
      <Text style={styles.sectionHeading}>{heading}</Text>
      {typeof children === 'string' ? (
        <Text style={styles.sectionBody}>{children}</Text>
      ) : (
        <View>{children}</View>
      )}
    </View>
  );
}

function SubSection({ heading, children }) {
  return (
    <View style={styles.subSection}>
      <Text style={styles.subSectionHeading}>{heading}</Text>
      <Text style={styles.sectionBody}>{children}</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    paddingTop: 56,
    paddingHorizontal: 24,
  },
  back: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 24,
  },
  backText: {
    fontSize: 15,
    color: '#0F6E56',
    fontWeight: '600',
  },
  content: {
    paddingBottom: 48,
  },
  title: {
    fontSize: 28,
    fontWeight: '700',
    color: '#0F6E56',
    marginBottom: 6,
  },
  lastUpdated: {
    fontSize: 12,
    color: '#AAAAAA',
    marginBottom: 28,
  },
  section: {
    marginBottom: 28,
  },
  sectionHeading: {
    fontSize: 15,
    fontWeight: '700',
    color: '#1A3C34',
    marginBottom: 10,
  },
  sectionBody: {
    fontSize: 14,
    color: '#666666',
    lineHeight: 22,
  },
  subSection: {
    marginBottom: 14,
    paddingLeft: 12,
    borderLeftWidth: 2,
    borderLeftColor: '#E8F0EE',
  },
  subSectionHeading: {
    fontSize: 13,
    fontWeight: '700',
    color: '#1A3C34',
    marginBottom: 4,
  },
});
